sudo: false
language: node_js
node_js:
  - 'node'
  - '8'
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - npm test
after_success:
  - ./node_modules/.bin/coveralls < coverage/lcov.info
